import Feed from "@/components/Feed";
import Modal from "@/components/Modal";
import Sidebar from "@/components/Sidebar";
import SinglePost from "@/components/SinglePost";
import Weather from "@/components/Weather";
import { AppContext } from "@/contexts/AppContext";
import Head from "next/head";
import React, { useContext } from "react";

const PostPage = () => {

    const [appContext] = useContext(AppContext)

    return (
        <div>
            <Head>
                <title>Tweet Reply</title>
                <meta name="description"
                content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="relative max-w-[1400px] mx-auto">
                <Sidebar />
                <div className="flex gap-6">
                    <SinglePost />
                    <Weather />
                   
                    {appContext?.isModalOpen && <Modal />}
                </div>
                
            </main>
        </div>
    )
}

export default PostPage