import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useSession } from 'next-auth/react'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import { AppContext } from '@/contexts/AppContext'
import { useContext } from 'react'
import Modal from '@/components/Modal'
import Weather from '@/components/Weather'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const {data: session} =useSession()
  const [appContext] = useContext(AppContext)

  if(!session) return <Login />

  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className='relative max-w-[1400px] mx-auto'>
        <Sidebar />
        <div className='flex gap-6'>
            <Feed />
            <Weather />
            {appContext?.isModalOpen && <Modal />}
        </div>
      </main>

    </>
  )
}
